version: '3.9'

services:
  applicationdb:
    image: postgres

  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: Server/WebAPI/Dockerfile

volumes:
  postgres_applicationdb:
  