services:
  applicationdb:
    container_name: applicationdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=applicationdb
    restart: always
    ports:
      - "4100:5432"
    volumes:
      - postgres_applicationdb:/var/lib/postgresql/data/

  webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__Database=Server=applicationdb;Port=5432;Database=applicationdb;User Id=postgres;Password=postgres;Include Error Detail=true
    ports:
      - "4000:8080"
    depends_on:
      - applicationdb
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  webapp:
    ports:
      - "3000:80"
    depends_on:
      - webapi