version: '3.9'

services:
  applicationdb:
    image: postgres

  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: Server/WebAPI/Dockerfile

  webapp:
    image: ${DOCKER_REGISTRY-}webapp
    build:
      context: ./Client/my-app
      dockerfile: Dockerfile

volumes:
  postgres_applicationdb:
  